"""add bank statements table

Revision ID: bank_statements_001
Revises: fix_migration_001
Create Date: 2024-12-14 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'bank_statements_001'
down_revision = 'fix_migration_001'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_statements',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('account_number', sa.String(length=50), nullable=True),
        sa.Column('transaction_date', sa.DateTime(), nullable=True),
        sa.Column('transaction_type', sa.String(length=20), nullable=True),
        sa.Column('amount', sa.Float(), nullable=True),
        sa.Column('balance', sa.Float(), nullable=True),
        sa.Column('counterparty', sa.String(length=200), nullable=True),
        sa.Column('description', sa.String(length=500), nullable=True),
        sa.Column('bank_name', sa.String(length=100), nullable=True),
        sa.Column('file_path', sa.String(length=500), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_bank_statements'))
    )
    op.create_index(op.f('ix_bank_statements_account_number'), 'bank_statements', ['account_number'], unique=False)
    op.create_index(op.f('ix_bank_statements_id'), 'bank_statements', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bank_statements_id'), table_name='bank_statements')
    op.drop_index(op.f('ix_bank_statements_account_number'), table_name='bank_statements')
    op.drop_table('bank_statements')
    # ### end Alembic commands ### 