"""change_amount_fields_to_float

Revision ID: f4881cfb8a19
Revises: add_invoice_items
Create Date: 2024-12-15 20:23:41.250124

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f4881cfb8a19'
down_revision = 'add_invoice_items'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_invoice_items_id', table_name='invoice_items')
    op.drop_table('invoice_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('quantity', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('unit', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('unit_price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name='fk_invoice_items_invoice_id_invoices', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_invoice_items')
    )
    op.create_index('ix_invoice_items_id', 'invoice_items', ['id'], unique=False)
    # ### end Alembic commands ###
